"""Initial migration 3.

Revision ID: eb8af0838c60
Revises: 5357bd7f2b20
Create Date: 2023-12-29 19:06:52.612559

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eb8af0838c60'
down_revision = '5357bd7f2b20'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.drop_column('colors')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.add_column(sa.Column('colors', sa.TEXT(), nullable=False))

    # ### end Alembic commands ###
